[BIOMAGE-2130] - Fix assign embedding
biomage-org/worker pull request #23
Opened 2022-09-13 23:25 UTC by aerlaut

# Description
Assign embedding in worker is showing the wrong embedding, because embedding is sorted by cells id, not by barcodes order. This causes trajectory analysis to mess up the order of the pseudotime.

# Details
#### URL to issue
https://biomage.atlassian.net/browse/BIOMAGE-2130

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR
https://github.com/biomage-org/ui/pull/44

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-09-14 08:14 UTC, saracastel commented on r/R/embedding.R
> -  embedding <- embedding_data[!vapply(embedding_data, is.null, logical(1))]
So we don't filter for nulls anymore? What happens with filtered cells? They will be ["NA", "NA"], but will still be present?

2022-09-14 08:33 UTC, aerlaut commented on r/R/embedding.R
> -  embedding <- embedding_data[!vapply(embedding_data, is.null, logical(1))]
We don't filter for nulls, because it turns out that nulls are not represented in R, i.e. R automatically removes the null values. This automatic removal of nulls messes up the indexing of the embedding. To preserve the indexing, null is replaced in the Python worker to ["NA", "NA"].

The NAs are removed when subsetting with the embedding cell_ids, because existing cell_ids will have embedding values.

2022-09-14 15:18 UTC, ivababukova requested changes
we need to add a unit test to test for this functionality to make sure we don't break this by mistake in the future.

2022-09-14 16:23 UTC, aerlaut commented
@ivababukova 

Monocle 3 uses the embedding to calculate pseudotime and then associating the value to the barcode. We assume that Monocle 3 assigns the correct pseudotime value. I've added a test which checks that the embedding is assigned to the correct cell_id and barcode. So, by transition, the test ensures that the pseudotime value is associated with the correct cell_id and barcode.

2022-09-14 23:08 UTC, gerbeldo approved these changes
Small comments, but looks good

2022-09-14 23:08 UTC, gerbeldo commented on r/R/embedding.R
> +  # cells_id is added by one because it is 0 indexed
Rephrase. Add 1 to cells_id because it's 0-index and embeddings is not.

2022-09-14 23:08 UTC, gerbeldo commented on r/tests/testthat/test-embedding.R
> +  expect_false(identical(old_embedding, new_embedding))
Where is new_embedding defined?

2022-09-14 23:08 UTC, gerbeldo commented on r/tests/testthat/test-embedding.R
> +  new_embedding <- Seurat::Embeddings(mock_seurat_object, reduction = "umap")
Oh, here it is. Should be moved up.

2022-09-14 23:11 UTC, gerbeldo commented on r/tests/testthat/test-embedding.R
> +  new_embedding <- Seurat::Embeddings(mock_seurat_object, reduction = "umap")
It will fail the tests. As a general suggestion, you should run the complete test (running the whole test_that function) when working interactively to see if the test actually passes, and be careful of the global environment.

2022-09-15 04:45 UTC, aerlaut commented on python/src/worker/tasks/trajectory_analysis_pseudotime.py
> +        # null values are not represented in R, so we have to convert it to something else
rephrased

2022-09-15 04:45 UTC, aerlaut commented on python/src/worker/tasks/trajectory_analysis_starting_nodes.py
> +        # null values are not represented in R, so we have to convert it to something else
rephrased

2022-09-15 04:45 UTC, aerlaut commented on r/R/embedding.R
> +  # cells_id is added by one because it is 0 indexed
Rephrased

2022-09-15 04:47 UTC, aerlaut commented on r/tests/testthat/test-embedding.R
> +  expect_false(identical(old_embedding, new_embedding))
Ah right, there's a switcharoo. `new_embedding` is defined below on line 163. This has to be moved to a later line.

2022-09-15 08:49 UTC, ivababukova commented on python/src/worker/tasks/trajectory_analysis_pseudotime.py
> +
better move this in the get_embedding` function. Otherwise, every time you use the get_embedding function, you will have to think about replacing NULL values with `"NA"`. Even better solution, if you can, is to modify the place where the embedding is calculated and added to S3 to insert `"NA"` instead of NULL values.

2022-09-15 09:16 UTC, aerlaut commented on python/src/worker/tasks/trajectory_analysis_pseudotime.py
> +
I did that initially, but then thought that we might need to get the embedding for other purposes, and it would not be good to apply this formatting. I would not also modify the embedding response to contain the string "NA" instead of `null` before storing it in S3. I believe `nulls` allow us to store the array in sparse representation in Javascript. 

It is only for R that we need to convert the `null` values to other representation, so I did this specifically where the R worker needs the embedding.

2022-09-15 13:53 UTC, merged