Add datadog
biomage-org/worker pull request #24
Opened 2022-09-21 15:31 UTC by aerlaut

# Description
Add Datadog container as sidecar

# Details
#### URL to issue
N/A

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR
N/A

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-09-30 12:46 UTC, kafkasl requested changes

2022-09-30 12:46 UTC, kafkasl commented on chart-infra/templates/datadog-sidecar-permissions.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
same issue as in the pipeline PR

2022-09-30 13:07 UTC, kafkasl approved these changes

2022-10-04 11:08 UTC, aerlaut commented on chart-infra/templates/datadog-sidecar-permissions.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
See replies and discussion in the comment: https://github.com/biomage-org/pipeline/pull/30/files#r984552629

2022-10-04 12:57 UTC, ivababukova commented on chart-infra/templates/pod-template.tpl
> +          - name: DD_KUBERNETES_KUBELET_NODENAME
this is aligned differently from here: https://github.com/biomage-org/pipeline/pull/30/files 
Which one of the two is correct?

2022-10-05 18:42 UTC, ivababukova commented on chart-infra/templates/worker-spawn-right-to-api.yaml
>  kind: RoleBinding
same here -- remove changes. Unless you are sure and have tested that they work

2022-10-06 06:27 UTC, ivababukova approved these changes

2022-10-07 09:21 UTC, merged