[BIOMAGE-2184] Improve DifferentialExpression work response schema
biomage-org/worker pull request #44
Opened 2022-11-24 09:36 UTC by StefanBabukov

# Description

# Details
#### URL to issue
https://biomage.atlassian.net/browse/BIOMAGE-2184

#### Link to staging deployment URL (or set N/A)

#### Links to any PRs or resources related to this PR

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-11-29 09:57 UTC, aerlaut commented on python/src/worker/tasks/differential_expression.py
> +        return Result({"total": result["full_count"], **result["gene_results"]})
What is the shape of `result["gene_results"]`?

2022-11-30 08:18 UTC, kafkasl requested changes

2022-11-30 12:38 UTC, StefanBabukov commented on python/src/worker/tasks/differential_expression.py
> +        return Result({"total": result["full_count"], **result["gene_results"]})
The shape is like this 
`  {"p_val": [1.496, 2.496, 3.496, 4.496, 5.496],
  "p_val_adj": [1.647, 2.647, 3.647, 4.647, 5.647],
  "logFC": [-1.427, -2.427, -3.427, -4.427, -5.427],
  "gene_names": ["A", "B", "C", "D", "E"],
  "Gene": ["EASAD0", "ENASD23", "EN34S", "ENSD33", "ENASD233"],
  "auc": ["0.1", "0.2", "0.3", "0.4", "0.5"],
  "pct_1": ["100", "90", "80", "70", "60"],
  "pct_2": ["100", "90", "80", "70", "60"]}`

2022-12-01 12:29 UTC, kafkasl approved these changes

2022-12-02 16:22 UTC, merged