[BIOMAGE-2108] Add overlay data for embeddings.
biomage-org/worker pull request #47
Opened 2022-11-25 22:00 UTC by gerbeldo

# Description
Simplifies and improves the metadata getter functions, and adds the getting of the required variables (number of genes and number of UMIs per cell)

# Details
#### URL to issue
https://biomage.atlassian.net/browse/BIOMAGE-2108

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

2022-11-28 16:18 UTC, saracastel commented on r/R/get_metadata_information.R
> +}
Are there any advantages to making two functions instead of a single function using nFeature_RNA/nCount_RNA as a parameter?

2022-11-28 17:54 UTC, gerbeldo commented on r/R/get_metadata_information.R
> +}
None, really. I thought about changing it but focused on making it more efficient, and just followed the original design. Happy to change it.

2022-11-28 21:52 UTC, gerbeldo commented on r/R/get_metadata_information.R
> +}
well, that involves quite a bit of refactoring for almost no benefit (changes in the UI and API as well). So I would not do it.

2022-11-29 08:08 UTC, saracastel commented on r/R/get_metadata_information.R
> +}
Ok, makes sense.

2022-11-29 11:00 UTC, saracastel approved these changes

2022-11-29 11:00 UTC, saracastel commented on r/R/get_metadata_information.R
> +#' extract doublet scores
```suggestion
#' Extract doublet scores
```
Sorry just for OCD

2022-11-29 11:00 UTC, saracastel commented on r/R/get_metadata_information.R
> +  complete_values[data$cells_id + 1] <- data@meta.data[, column]
I think this is very smart :)

2022-11-29 22:00 UTC, gerbeldo commented on r/R/get_metadata_information.R
> +#' extract doublet scores
❤️

2022-11-29 22:07 UTC, gerbeldo commented on r/R/get_metadata_information.R
> +  complete_values[data$cells_id + 1] <- data@meta.data[, column]
more ❤️. I spent quite a bit of time on this! nearly broke my brain but I ended up quite happy about it (I even sent a screenshot of this block's diff to @cosa65 on friday night 😁 ), so thank you! I think we could use a similar idea to make the expression task even faster, but I had to stop (and I'm not sure if it's worth it, it's pretty efficient as it currently is, and it's not a heavy task).

And I might be wrong, but I think I read that pre-allocating vectors/lists in R and then modifying them is way more efficient than making them grow iteratively.

2022-11-30 07:47 UTC, kafkasl commented on r/R/get_metadata_information.R
> +  complete_values[data$cells_id + 1] <- data@meta.data[, column]
do we need to send back the nulls? I assume the nulls are the cells that are filtered out. On the note of pre-allocating vectors, an important bit is that doing some performance analysis one of the biggest pain points is when you have to cast a vector to a new type. If you are creating a vector of `NA` afaik it will be a `logical` vector, when you assign numbers to it, it will have to be casted into a `num` vector which will be a costly operation.  You can see this in the first example [here](https://cran.r-project.org/web/packages/profmem/vignettes/profmem.html).

To fix that initialize the vector to `NA_real_` which will create a numeric vector right away.

2022-11-30 07:52 UTC, kafkasl reviewed
The PR looks very good. I only added a performance improvement. 
However, it bothers me that we are sending all the filtered cells back as nulls. After removing the configure embeddings / data integration miniplots those steps still work pretty bad. One of the issues is probably that the computing is just slow, but the other seems to be how we processed the receive data. I'm wondering whether we should already remove those `null` and just send the data we need (not necessarily in this PR). Opinions? @cosa65

2022-11-30 07:53 UTC, kafkasl requested changes
just requesting changes to make sure you do the performance improvement before merging as it's already approved

2022-11-30 10:05 UTC, gerbeldo commented on r/R/get_metadata_information.R
> +  complete_values[data$cells_id + 1] <- data@meta.data[, column]
This is amazing. I knew about NAs being some kind of logical, i did not think about the conversion nor know that there were typed NAs! Thanks.

Regarding ito the null necessity, I'm not sure, I thought about that. This is based on the processed object. The embedding to overlay is also based on the processed object (which means that all filtered cells are already not there in both cases. The UI could assume cell_id by using the order of the dense (but shorter) vector, but I'm not convinced. The other option is to send a "sparse vector" the values and cell_ids. For big, heavily filtered experiments (more that 50% filtered) we would be sending "less stuff".

Also want @cosa65 thoughts.

2022-11-30 15:23 UTC, kafkasl commented on r/R/get_metadata_information.R
> +  complete_values[data$cells_id + 1] <- data@meta.data[, column]
I think that sending the two vectors `values` and `cell_ids` should be good. Although if the processed object already doesn't have the filtered out cells, we don't really need the IDs for anything do we? I mean for the overlays you just have the coordinates and the overlay values as retrieved from the column from the seurat object. Or do we use the indices in the UI?

2022-11-30 15:24 UTC, kafkasl commented on r/R/get_metadata_information.R
> +  complete_values[data$cells_id + 1] <- data@meta.data[, column]
in any case, having both `values` & `cell_ids` should be better already and if the UI ignores the `cell_ids` because it turns out they are not needed the all the better (and we can remove them / have a parameter to send only the values)

2022-12-08 12:59 UTC, merged